### ISSUE TITLE
Can't find variable: React on ios

### ISSUE THREAD

**Issue by sejr1996** [idrisssakhi/blurView#2]
When running on ios you have an error:
Can't find variable: React

I add the following line:
`import React from 'react';`

As shown in the following picture:
<img width="665" alt="Captura de Pantalla 2022-05-26 a la(s) 08 22 33" src="https://user-images.githubusercontent.com/75812071/170496555-bb3f930c-f555-4e33-97a7-9d7922d381ca.png">

**Comment by idrisssakhi** [comment]
This issue is resolved thanks to @slauzinho
