### ISSUE TITLE
Could not find com.github.Dimezis:BlurView:version-2.0.0

### ISSUE THREAD

**Issue by andresribeiro** [idrisssakhi/blurView#4]
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDevDebugAarMetadata'.
> Could not resolve all files for configuration ':app:devDebugRuntimeClasspath'.
   > Could not find com.github.Dimezis:BlurView:version-2.0.0.
     Required by:
         project :app > project :rn-id-blurview
```

**Comment by idrisssakhi** [comment]
Would you give me more information please, 
RN version ... etc

**Comment by idrisssakhi** [comment]
@andresribeiro if you send me your code, it can help a lot to resolve the issue

**Comment by andresribeiro** [comment]
@idrisssakhi i just tried to install and run on android without modifying any code, but i'll try to create a new project to see if it works

**Comment by andresribeiro** [comment]
i was trying on a project that is using 0.67.4 but it worked on a new one using 0.68.2
