### ISSUE TITLE
blurType prop doesn't work on Android

### ISSUE THREAD

**Issue by ariangel** [idrisssakhi/blurView#5]
I'm trying to use light and xlight blurType. On iOS it works well but on Android there's no effect. 

Version: 1.1.1

**Comment by idrisssakhi** [comment]
Hey 👋  @ariangel 

Would you send me a code simple please, and if am not mistaken xlight is not supported on android. please read the DOC.

**Comment by ariangel** [comment]
Hey @idrisssakhi 

The doc says that light, xlight and dark types are supported but none of these is working on Android. I tried set a white background with opacity to simulate the light and xlight but this removes the blur effect.

**Comment by idrissakhi** [comment]
Would you send the code you are using please, because i am using it on React Native v 0.68 and it works fine on both platforms.

**Comment by andresribeiro** [comment]
@idrisssakhi BlurView it's not yet compatible with the new architecture, right?

**Comment by idrissakhi** [comment]
@andresribeiro no not yet, you are welcome if you want to add that 🙂😉.

**Comment by idrisssakhi** [comment]
You can't use overlayColor and blurType at the same time on android side
