### ISSUE TITLE
Blur radius on iOS

### ISSUE THREAD

**Issue by yolpsoftware** [idrisssakhi/blurView#8]
If I understand it correctly, this library does not offer a blur radius on its `BlurView`. I suspect the reason is that [iOS itself does not offer such a BlurView](https://stackoverflow.com/questions/25529500/how-to-set-the-blurradius-of-uiblureffectstyle-light).

However, it seems that at least SwiftUI offers a solution to [blur something and define the blur radius](https://developer.apple.com/documentation/swiftui/view/blur(radius:opaque:)).

Does anybody know, is it possible to pack a SwiftUI component into a React Native library?

**Comment by idrisssakhi** [comment]
it does propose BlurRadius, please check the library documentation.

**Comment by yolpsoftware** [comment]
Yes, but isn't `blurRadius` supported on Android only?

So, as you wrote in issue #9, just use `blurAmount` on iOS.
